spring:
  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/mercado_livro?createDatabaseIfNotExist=true
    username: root
    password: root
  jackson:
    default-property-inclusion: non_null
